# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run testcases

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
      - bugfix/*
      - issues/*
  pull_request:
    branches:
      - master 
      - develop

jobs:
  build:

    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}.

    steps:
    - uses: actions/checkout@v6
    - name: Install uv and set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Update system
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --no-group docs --no-install-project
    - name: Static checks
      run: |
        uv run mypy basana
        uv run ruff check
    - name: Run testcases
      run: |
        uv run pytest -vv --cov --cov-config=setup.cfg --durations=10